In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from collections import Counter

In [3]:
tfidf_df = pd.read_csv(r"D:\TFG\tfg_git\data\tf_idf\news_processed_tfidf_fulldataset.csv")
tfidf_df_v3 = pd.read_csv(r"D:\TFG\tfg_git\data\tf_idf\news_processed_tfidfv2_fulldataset.csv")

In [4]:
tfidf_df

,level_0,aaron,abc,abc_news,ability,abortion,abortion_right,abraham,absence,abuse,...,york_times,yorker,youk,young,young_people,young_voter,youth,youtube,zealand,zone
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000
1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000
2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000
3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000
4,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26239,26496,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.05032
26240,26497,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000
26241,26498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000
26242,26499,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000
26243,26500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.052105,0.0,0.0,0.0,0.0,0.00000

In [5]:
import numpy as np

feature_names = tfidf_df.columns.tolist()

# loop through each row of the matrix and create a list of words for that row
word_lists = []
for row in range(tfidf_df.shape[0]):
    # get the indices of the non-zero elements in the row
    col_indices = np.nonzero(tfidf_df.iloc[row].values)[0]
    # create a list of words for the row
    words = [feature_names[col] for col in col_indices]
    word_lists.append(words)

word_lists_news = word_lists

In [6]:
len(word_lists_news)

26244

In [7]:
full_list = [item for sublist in word_lists_news for item in sublist]

In [8]:
full_list_ngrams = [item for item in full_list if '_' in str(item)]

In [9]:
ngrams_count = Counter(full_list_ngrams)

In [10]:
sorted_ngrams_count = sorted(ngrams_count.items(), key=lambda x: x[1], reverse=True)

In [11]:
for word, count in sorted_ngrams_count[:20]:
    print(f"{word}: {count}")

level_0: 26243
donald_trump: 20282
president_donald: 14947
president_donald_trump: 14115
bernie_sanders: 10638
new_york: 8719
white_house: 8315
joe_biden: 6779
vice_president: 6272
last_year: 5852
health_care: 5327
presidential_candidate: 4962
new_hampshire: 4944
elizabeth_warren: 4868
pete_buttigieg: 4619
president_trump: 4564
democratic_party: 4368
former_vice: 4255
sen_bernie: 4234
former_vice_president: 4234

In [12]:
for word, count in sorted_ngrams_count[:20]:
    print(f"{word}: {count}")

level_0: 26243
donald_trump: 20282
president_donald: 14947
president_donald_trump: 14115
bernie_sanders: 10638
new_york: 8719
white_house: 8315
joe_biden: 6779
vice_president: 6272
last_year: 5852
health_care: 5327
presidential_candidate: 4962
new_hampshire: 4944
elizabeth_warren: 4868
pete_buttigieg: 4619
president_trump: 4564
democratic_party: 4368
former_vice: 4255
sen_bernie: 4234
former_vice_president: 4234

### The top 15 ngrams created with the second case (not proper nouns)

In [13]:
import numpy as np

feature_names = tfidf_df_v3.columns.tolist()

# loop through each row of the matrix and create a list of words for that row
word_lists = []
for row in range(tfidf_df_v3.shape[0]):
    # get the indices of the non-zero elements in the row
    col_indices = np.nonzero(tfidf_df_v3.iloc[row].values)[0]
    # create a list of words for the row
    words = [feature_names[col] for col in col_indices]
    word_lists.append(words)

word_lists_news = word_lists

In [14]:
full_list = [item for sublist in word_lists_news for item in sublist]
full_list_ngrams = [item for item in full_list if '_' in str(item)]
ngrams_count = Counter(full_list_ngrams)
sorted_ngrams_count = sorted(ngrams_count.items(), key=lambda x: x[1], reverse=True)
for word, count in sorted_ngrams_count[:20]:
    print(f"{word}: {count}")

level_0: 26251
last_year: 5855
presidential_candidate: 4954
health_care: 4688
vice_president: 4603
last_week: 4112
former_vice: 3943
climate_change: 3592
former_vice_president: 3550
democratic_presidential_candidate: 3056
first_time: 3004
democratic_candidate: 2547
last_month: 2501
democratic_party: 2267
general_election: 2033
impeachment_trial: 2031
presidential_election: 1983
presidential_campaign: 1909
former_mayor: 1893
federal_government: 1794